### ISSUE TITLE
Translation game

### ISSUE THREAD

**Issue by criconhelp** [Asvel/tacticsogre-datamining#1]
Can I use this tool to translate the game after build?

**Comment by Asvel** [comment]
Do you mean to translate the game into another language?
This project is focused on extracting various data from the game, it could provide some useful information to you, but it can't directly help you to editing the game.
For game editing, you could refer to this project: <https://github.com/gibbed/Gibbed.LetUsClingTogether>.

**Comment by criconhelp** [comment]
Yes there is a desire to translate into another language. At the moment, I'm studying the general base about the availability of the toolkit for the game Tactics Ogre: Reborn.

Used the gibbed tool, but it is under development. 

It was able to decrypt files from the container, but cannot extract files from the "localize" container in .etxt format 

The same goes for fonts. After the decryption the file en-us.bin from the folder Font/en-us.dat has a size of 31mb and most likely contains the fonts of the game, but so far could not be extracted from this container.

**Comment by Asvel** [comment]
The inner structure of .etxt format is very straightforward, you can view it in ImHex with [this](
https://github.com/Asvel/tacticsogre-datamining/blob/master/imhex-patterns/patterns/tacticsogre.txte.hexpat).

But encoding of the text strings is not entirely UTF-8, there are several types control character inside it, I have parsed one type of them, you can view at [here](https://github.com/Asvel/tacticsogre-datamining/blob/master/extracts/ExtractText/GameTextEncoding.cs).

I don't know anything about the fonts either, sorry.

**Comment by criconhelp** [comment]
Thank you, I will look for a solution to the issue of unpacking fonts.
