### ISSUE TITLE
Obfuscate .pack file back to .dat

### ISSUE THREAD

**Issue by MrVtR** [Asvel/tacticsogre-datamining#2]
Hello, it's possible to make a script to obfuscate back the file?
I was looking at the Deobfuscate script, but didn't understand much of the C# Compression lib to make the obfuscation here on my own.

I tested making a change to the .pack file and placing it in the game folder(as .pack and renamed to .dat), but the game did not load it, so I suppose it is necessary to obfuscate the file back to be able to run modificications in the game
If you have some time to do it, would be great to test some mods

**Comment by Asvel** [comment]
This project is focused on extracting various data from the game, not the opposite direction.

You could try this: [Gibbed.Reborn.EncryptData](https://github.com/gibbed/Gibbed.LetUsClingTogether/tree/main/projects/Gibbed.Reborn.EncryptData), it looks like a obfuscator.

**Comment by MrVtR** [comment]
> This project is focused on extracting various data from the game, not the opposite direction.
> 
> You could try this: [Gibbed.Reborn.EncryptData](https://github.com/gibbed/Gibbed.LetUsClingTogether/tree/main/projects/Gibbed.Reborn.EncryptData), it looks like a obfuscator.

Sadly it didn't work. The file gets encrypted indeed, but the size doesn't change(pack to encrypted pack) and the game doesn't apply the texts mod that I'm testing. But thanks anyway!
The .pack is the deobfuscated file that ur tool generated and the .pack2 file is from Gibbed's tool above
![image](https://user-images.githubusercontent.com/30987772/205332955-1f7f5bf8-ca9e-43ed-9ef5-36cd32ca2f3e.png)

**Comment by Asvel** [comment]
It should be zipped first like [this](https://github.com/gibbed/Gibbed.LetUsClingTogether/blob/93c4b8d493015719ed0b7dc6aef7ee20dc7bab4d/projects/Gibbed.LetUsClingTogether.PackFileTable/Program.cs#L233).
The game seems to have some restriction on compression details, but I haven't look it as it's irrelevant for extracting.
